package de.mss.license;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import org.junit.Test;

import de.mss.license.exception.LicenseException;

public class LicenseKeyTest {

   @Test
   public void testOk() throws LicenseException {
      LicenseKey lk = new LicenseKey("3754667d-017f-49d2-bb62-0de1f994e49");

      assertEquals("LicenseKey", "3754667d-017f-49d2-bb62-0de1f994e49", lk.getLicenseKey());
      assertEquals("LicenseType", LicenseType.FREE_LICENSE, lk.getLicenseType());
      assertEquals("License Version", 1, lk.getLicenseVersion());
      assertEquals("Control Sum", 38116, lk.getControlSum());
   }


   @Test
   public void testWrongControlByte() {
      try {
         @SuppressWarnings("unused")
         LicenseKey lk = new LicenseKey("3754667d-017f-49d2-bb62-0de1f994e48");
         fail();
      }
      catch (LicenseException e) {
         assertEquals("ErrorCode", 3000, e.getError().getErrorCode());
         assertEquals("ErrorText", "wrong license key", e.getAltErrorText());
      }
   }


   @Test
   public void testWrongFormat() {
      try {
         @SuppressWarnings("unused")
         LicenseKey lk = new LicenseKey("3754667d-017f-49d2-bb62");
         fail();
      }
      catch (LicenseException e) {
         assertEquals("ErrorCode", 3000, e.getError().getErrorCode());
         assertEquals("ErrorText", "wrong license key format", e.getAltErrorText());
      }
   }


   @Test
   public void testNull() {
      try {
         @SuppressWarnings("unused")
         LicenseKey lk = new LicenseKey(null);
         fail();
      }
      catch (LicenseException e) {
         assertEquals("ErrorCode", 2, e.getError().getErrorCode());
         assertEquals("ErrorText", "no LicenseKey given", e.getAltErrorText());
      }
   }


}
